# version: '3.8' <-- REMOVIDO (Obsoloso)

services:
  db:
    image: postgres:15-alpine
    container_name: micro_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=micro_db
    ports:
      - "5433:5432"  
    networks:
      - micro-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    container_name: micro_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns,apigateway,s3,lambda
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  postgres_data:
  localstack_data: